### ISSUE TITLE
[개선] CD workflow 개선

### ISSUE THREAD

**Issue by greatSumini** [DEV-MUGLES/pickk-chrome#19]
```yaml
      # 배포서버에 ssh로 접속해서 pull-build-restart한다.
      - name: ssh pull-build-deploy
        uses: appleboy/ssh-action@master
        # ssh 접속을 위해 필요한 HOST, USERNAME, SSH_PRIVATE_KEY는
        # github 저장소 secrets에 등록해둔다
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd pickk-chrome/
            git pull origin master
            sudo npm install -g yarn
            yarn install
            pm2 restart app
```

현재 instance에 ssh 접속해서 배포 갱신하는 과정이 조금 원시적입니다.
ssh 접속 - git 명령어 단순 실행이 아닌
좀 더 나은 방향으로 발전시켜볼 수 있을 것 같아유
